package pe.one.pucp.supermercado.ui;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import pe.one.pucp.supermercado.controller.MainUIController;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created with IntelliJ IDEA.
 * User: lmiguelmh
 * Date: 14/10/14
 * Time: 09:50 PM
 * To change this template use File | Settings | File Templates.
 */
@Component
public class MainUI {

    private JPanel mainPanel;
    private JButton listarPersonalButton;
    private JButton agregarPersonalButton;
    private JButton listarProductosButton;
    private JButton agregarProductoButton;
    private JLabel sampleLabel;
    private JButton modificarPersonalButton;

    // 1 controller per view
    @Autowired
    MainUIController controller;

    public MainUI() {
        listarPersonalButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                controller.listarPersonalClick();
            }
        });
        agregarPersonalButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                controller.agregarPersonalClick();
            }
        });
        modificarPersonalButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                controller.modificarPersonalClick();
            }
        });
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public void setLabelText(String text) {
        sampleLabel.setText(text);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        listarPersonalButton = new JButton();
        listarPersonalButton.setText("Listar Personal");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(listarPersonalButton, gbc);
        agregarPersonalButton = new JButton();
        agregarPersonalButton.setText("Agregar Personal");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(agregarPersonalButton, gbc);
        listarProductosButton = new JButton();
        listarProductosButton.setText("Listar Productos");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(listarProductosButton, gbc);
        agregarProductoButton = new JButton();
        agregarProductoButton.setText("Agregar Producto");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(agregarProductoButton, gbc);
        sampleLabel = new JLabel();
        sampleLabel.setText("pe-text");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        mainPanel.add(sampleLabel, gbc);
        modificarPersonalButton = new JButton();
        modificarPersonalButton.setText("Modificar Personal");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(modificarPersonalButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
